version: "3.9"

services:
  home-assistant:
    container_name: Home-Assistant-Container
    image: ghcr.io/home-assistant/home-assistant:stable
    entrypoint: /init
    restart: unless-stopped

    environment:
      TZ: America/New_York
      LANG: C.UTF-8

    volumes:
      - /mnt/user/appdata/Home-Assistant-Container:/config

    networks:
      br2:
        ipv4_address: 192.168.20.2

    ports:
      - "8123:8123"
